channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.0
  - pip
  - pandas==0.24.2
  - pip:
    - coveralls==1.3.0
    - paramiko==2.4.2
    - html5lib==1.0.1
    - lxml==4.2.4
    - bs4==0.0.1
    - SQLAlchemy==1.3.0
    - PyMySQL==0.9.2
    - slackclient==1.2.1
    - asana==0.8.0
    - matplotlib==2.2.3
    - unittest2==1.1.0
    - Jinja2==2.10.1
    - gviz-api==1.9.0
    - xlrd==1.1.0
    - jsonschema==2.6.0
    - sphinx_rtd_theme==0.4.3
    - deeptools==3.2.1
