channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.5
  - pip
  - pip:
    - coveralls==1.3.0
    - html5lib==1.0.1
    - lxml==4.2.4
    - bs4==0.0.1
    - SQLAlchemy==1.2.11
    - PyMySQL==0.9.2
    - matplotlib==2.2.3
    - unittest2==1.1.0
    - Jinja2==2.10
    - gviz-api==1.9.0
    - xlrd==1.1.0
    - jsonschema==2.6.0
    - numba==0.39.0
    - pandas==0.23.0
    - numpy==1.14.0
